# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout.addWidget(self.menu)
        self.janelaPrincipal = QtWidgets.QFrame(self.centralwidget)
        self.janelaPrincipal.setMaximumSize(QtCore.QSize(500, 16777215))
        self.janelaPrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.janelaPrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.janelaPrincipal.setObjectName("janelaPrincipal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.janelaPrincipal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailUserData = QtWidgets.QFrame(self.janelaPrincipal)
        self.emailUserData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailUserData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailUserData.setObjectName("emailUserData")
        self.startPrograma = QtWidgets.QFrame(self.emailUserData)
        self.startPrograma.setGeometry(QtCore.QRect(0, 230, 471, 241))
        self.startPrograma.setMaximumSize(QtCore.QSize(500, 16777215))
        self.startPrograma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startPrograma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.startPrograma.setObjectName("startPrograma")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.startPrograma)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputPortaArduino = QtWidgets.QLineEdit(self.startPrograma)
        self.inputPortaArduino.setObjectName("inputPortaArduino")
        self.verticalLayout_2.addWidget(self.inputPortaArduino)
        self.saidaGraficos = QtWidgets.QTimeEdit(self.startPrograma)
        self.saidaGraficos.setTime(QtCore.QTime(1, 0, 0))
        self.saidaGraficos.setObjectName("saidaGraficos")
        self.verticalLayout_2.addWidget(self.saidaGraficos)
        self.btnIniciar = QtWidgets.QPushButton(self.startPrograma)
        self.btnIniciar.setObjectName("btnIniciar")
        self.verticalLayout_2.addWidget(self.btnIniciar)
        self.barraProgresso = QtWidgets.QProgressBar(self.startPrograma)
        self.barraProgresso.setProperty("value", 0)
        self.barraProgresso.setObjectName("barraProgresso")
        self.verticalLayout_2.addWidget(self.barraProgresso)
        self.saidaStatus = QtWidgets.QLabel(self.startPrograma)
        self.saidaStatus.setText("")
        self.saidaStatus.setObjectName("saidaStatus")
        self.verticalLayout_2.addWidget(self.saidaStatus)
        self.verticalLayout.addWidget(self.emailUserData)
        self.horizontalLayout.addWidget(self.janelaPrincipal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Estação Metereologica Fat83DotCom"))
        self.inputPortaArduino.setPlaceholderText(_translate("MainWindow", "Porta Arduíno"))
        self.saidaGraficos.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
